theme: minima
title: User Engagement Analytics
author: Nate Fernandez
email: nate.fernandez23@gmail.com
description: > This website shows you user engagement for any class
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: realDonaldTrump # DO NOT include the @ character, or else the build will fail!
github_username:  natefernandez # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
